spring:
  cloud:
    function:
      definition: sendTestData
    stream:
      bindings:
        sendTestData-out-0:
          destination: dataIn
          binder: kafka1
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 1
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:29092,localhost:39092
                      transaction:
                        transactionIdPrefix: transactionTestPrefix_${HOSTNAME:localhost}-
                        producer:
                          compressionType: gzip

logging:
  level:
    root: debug
